# Generated by Django 3.2 on 2021-04-16 05:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Name')),
                ('episodes', models.SmallIntegerField()),
                ('start_airing', models.DateField()),
                ('end_airing', models.DateField()),
                ('starting_season', models.CharField(max_length=100, verbose_name='Name')),
                ('broadcast_time', models.DateField()),
                ('licensors', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20), size=20)),
                ('producers', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20), size=20)),
                ('studios', models.CharField(max_length=50)),
                ('sources', models.CharField(max_length=50)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20), size=20)),
                ('duration', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('score_by', models.IntegerField()),
                ('members', models.IntegerField()),
                ('favorites', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
